version: '3.9'

services:

  # The 'setup' service runs a one-off script which initializes the
  # 'logstash_internal' and 'kibana_system' users inside Elasticsearch with the
  # values of the passwords defined in the '.env' file.
  #
  # This task is only performed during the *initial* startup of the stack. On all
  # subsequent runs, the service simply returns immediately, without performing
  # any modification to existing users.
  
        
  attacker:
    build:
      context: Attacker/
      dockerfile: DockerfileAttacker
    networks:
      companyABC:
        ipv4_address: 172.16.0.9
      
networks:
  companyABC:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
